sudo: required
services:
  - docker

before_install:
  - tmpdaemon=$(mktemp)
  - sudo jq '."registry-mirrors" += ["https://mirror.gcr.io"]' /etc/docker/daemon.json > $tmpdaemon
  - sudo mv $tmpdaemon /etc/docker/daemon.json
  - sudo systemctl daemon-reload
  - sudo systemctl restart docker
  - docker system info
  - docker build -t testme -f Dockerfile1.dev .

script:
  - docker run -e CI=true testme npm run test -- --coverage
