sudo: required
services:
  - docker

before_install:
  - echo 'DOCKER_OPTS="$DOCKER_OPTS --registry-mirror=https://mirror.gcr.io"'
  - sudo service docker restart
  - docker build -t testme -f Dockerfile1.dev .

script:
  - docker run -e CI=true testme npm run test -- --coverage
